language: node_js
node_js:
  - '0.10'

addons:
   firefox: "23.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"



script:
  - npm run test-pre
  - 'if [[ $TRAVIS_PULL_REQUEST == ''false'' ]]; then { npm run test-remote; }; else { npm run test-local; }; fi'
  - firefox --version
